version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 25
