import {
  AlertTriangle,
  ArrowRight,
  ArrowUpDown,
  Book,
  Check,
  ChevronLeft,
  ChevronRight,
  CreditCard,
  Edit,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LockKeyhole,
  LucideIcon,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  Pizza,
  Plus,
  Receipt,
  Settings,
  Store,
  SunMedium,
  Trash,
  User,
  X,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Store,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  lock: LockKeyhole,
  check: Check,
  product: Package,
  category: Book,
  customer: User,
  order: Receipt,
  minus: Minus,
  arrow: ArrowUpDown,
  more: MoreHorizontal,
  edit: Edit,
}
