services:
  aspire-dashboard:
    container_name: "aspire-dashboard"
    image: "mcr.microsoft.com/dotnet/aspire-dashboard:8.0"
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
    ports:
      - target: 18888
        published: 18888
    restart: unless-stopped
  db:
    container_name: "db"
    image: "docker.io/ankane/pgvector:latest"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "db"
    ports:
      - target: 5432
        published: 5432
    restart: unless-stopped
  redis:
    container_name: "redis"
    image: "docker.io/library/redis:7.2"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "redis"
    ports:
      - target: 6379
        published: 6379
    command:
      - "--save"
      - "60"
      - "1"
    restart: unless-stopped
  identity-service:
    container_name: "identity-service"
    image: "identity-service:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__redis: "redis:6379"
      ConnectionStrings__userdb: "Host=db;Port=5432;Username=root;Password=NashTech@2024;Database=userdb"
      Provider__Google__ClientId: "${GOOGLE_CLIENT_ID}"
      Provider__Google__ClientSecret: "${GOOGLE_CLIENT_SECRET}"
      Client__Backoffice: "http://backoffice:8000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "identity-service"
    ports:
      - target: 8080
        published: 10000
      - target: 8443
        published: 10001
    restart: unless-stopped
  bff:
    container_name: "bff"
    image: "bff:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__redis: "redis:6379"
      ReverseProxy__Clusters__api__Destinations__api__Address: "/api/v1"
      BFF__Api__RemoteUrl: "/api/v1/categories"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "bff"
    ports:
      - target: 8080
        published: 10002
      - target: 8443
        published: 10003
    restart: unless-stopped
  api-service:
    container_name: "api-service"
    image: "api-service:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__redis: "redis:6379"
      ConnectionStrings__shopdb: "Host=db;Port=5432;Username=root;Password=NashTech@2024;Database=shopdb"
      ConnectionStrings__openai: ${OPENAI_CONN}
      SmtpSettings__Secret: "${SMTP_SECRET}"
      AiOptions__OpenAi__EmbeddingName: "text-embedding-3-small"
      AzuriteSettings__ConnectionString: "{storage.outputs.blobEndpoint}"
      CorsSettings__Backoffice: "http://backoffice:8000"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "api-service"
    ports:
      - target: 8080
        published: 10004
      - target: 8443
        published: 10005
    restart: unless-stopped
  backoffice:
    container_name: "backoffice"
    image: "backoffice:latest"
    environment:
      NODE_ENV: "development"
      PORT: "8000"
      BROWSER: "none"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "backoffice"
    ports:
      - target: 8000
        published: 3000
    restart: unless-stopped
  storefront:
    container_name: "storefront"
    image: "storefront:latest"
    environment:
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
      OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
      ConnectionStrings__redis: "redis:6379"
      ConnectionStrings__openai: "${OPENAI_CONN}"
      SmartComponents__ApiKey: "${OPENAI}"
      StripeSettings__StripeSecretKey: "${STRIPE_SECRET}"
      AiOptions__OpenAi__ModelName: "gpt-4-turbo"
      StripeSettings__StripeWebhookSecret: "${STRIPE_WEBHOOK}"
      BaseApiEndpoint: "/api/v1"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://aspire-dashboard:18889"
      OTEL_SERVICE_NAME: "storefront"
    ports:
      - target: 8080
        published: 10006
      - target: 8443
        published: 10007
    restart: unless-stopped
