---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: docker.io/ankane/pgvector:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: tcp
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-env
            - secretRef:
                name: db-secrets
      terminationGracePeriodSeconds: 180
      automountServiceAccountToken: false
