---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  labels:
    app: bff
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: bff
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bff
    spec:
      containers:
        - name: bff
          image: bff:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          envFrom:
            - configMapRef:
                name: bff-env
            - secretRef:
                name: bff-secrets
      terminationGracePeriodSeconds: 180
      automountServiceAccountToken: false
