resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: bff-env
    literals:
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ReverseProxy__Clusters__api__Destinations__api__Address=/api/v1
      - BFF__Api__RemoteUrl=/api/v1/categories
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_SERVICE_NAME=bff
      - ASPNETCORE_URLS=http://+:8080;

secretGenerator:
  - name: bff-secrets
    envs:
      - .bff.secrets
