resources:
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: storefront-env
    literals:
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
      - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - AiOptions__OpenAi__ModelName=gpt-4-turbo
      - BaseApiEndpoint=/api/v1
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_SERVICE_NAME=storefront
      - ASPNETCORE_URLS=http://+:8080;

secretGenerator:
  - name: storefront-secrets
    envs:
      - .storefront.secrets
