---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  labels:
    app: api-service
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: api-service:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          envFrom:
            - configMapRef:
                name: api-service-env
            - secretRef:
                name: api-service-secrets
      terminationGracePeriodSeconds: 180
      automountServiceAccountToken: false
